# SPDX-FileCopyrightText: 2020-2021 Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
#
# SPDX-License-Identifier: CC0-1.0

[tool.black]

line-length = 94

[tool.pylint."MASTER"]

persistent = "yes"
unsafe-load-any-extension = "no"

jobs=4

[tool.pylint."MESSAGES CONTROL"]

disable=[
    "bad-continuation",
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "duplicate-code",
]

[tool.coverage.run]

branch=true
relative_files=true
source=["src"]

[tool.coverage.report]

fail_under=80.0

[tool.coverage.html]

show_contexts=true
