from __future__ import annotations

import dataclasses
from typing import Optional, Union

import watchfiles
from watchdog.events import FileSystemEvent  # type: ignore

from mewbot.core import InputEvent


@dataclasses.dataclass
class FileSystemInputEvent(InputEvent):
    """
    Base class for generic input events generated by the file system.
    """

    # equivalent to FileSystemEvent, tuple[watchfiles.Change, str], None]
    base_event: Optional[Union[FileSystemEvent, tuple[watchfiles.Change, str]]]
