# SPDX-FileCopyrightText: 2023 Mewbot Developers <mewbot@quicksilver.london>
#
# SPDX-License-Identifier: BSD-2-Clause

"""
Provides base objects for the file system monitoring subsystem.

Includes valid InputEvents for the file system monitor.
"""

from typing import Optional, Union

import dataclasses
from pathlib import Path

import watchfiles
from watchdog.events import FileSystemEvent  # type: ignore

from mewbot.api.v1 import InputEvent


@dataclasses.dataclass
class FSInputEvent(InputEvent):
    """
    Base class for generic input events generated by the file system.
    """

    # equivalent to FileSystemEvent, tuple[watchfiles.Change, str], None]
    base_event: Optional[Union[FileSystemEvent, tuple[watchfiles.Change, str]]]


@dataclasses.dataclass
class FileFSInputEvent(FSInputEvent):
    """
    Base class for file related input events generated by the file system.
    """

    path: str


#
# --------------------------------------
# - INPUT - WATCHING A LOCATION
# --------------------------------------
#

# - FILE AT LOCATION


@dataclasses.dataclass
class FileCreatedAtWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A file has been created on the system within a dir being monitored.
    """


@dataclasses.dataclass
class FileUpdatedAtWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A file has been updated at the location being watched.
    """


@dataclasses.dataclass
class FileMovedToWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A file has been moved to the location being watched.
    """

    file_src: str


@dataclasses.dataclass
class FileMovedFromWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A file has been moved to the location being watched.
    """

    file_src: str


@dataclasses.dataclass
class FileDeletedFromWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A file has been deleted from the location being watched.
    """


# - DIR AT LOCATION


@dataclasses.dataclass
class DirCreatedAtWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A directory has been created on the system within a dir being monitored.
    """


@dataclasses.dataclass
class DirUpdatedAtWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A dir has been updated at the location being watched.
    """


@dataclasses.dataclass
class DirMovedToWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A dir has been moved to the location being watched.
    """

    file_src: str


@dataclasses.dataclass
class DirMovedFromWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A dir has been moved away from the location being watched.
    """

    file_src: str


@dataclasses.dataclass
class DirDeletedFromWatchLocationFSInputEvent(FileFSInputEvent):
    """
    A dir has been deleted from the location being watched.
    """


# - WITHIN THE DIR AT LOCATION


@dataclasses.dataclass
class FileCreatedWithinWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A file has been created on the system within a dir being monitored.
    """


@dataclasses.dataclass
class FileUpdatedWithinWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A file has been updated at the location being watched.
    """


@dataclasses.dataclass
class FileMovedWithinWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A file has been moved to the location being watched.
    """

    file_src: str
    file_dst: str


@dataclasses.dataclass
class FileMovedOutsideWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A file has been moved to the location being watched.
    """

    file_src: str


@dataclasses.dataclass
class FileDeletedWithinWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A file has been deleted from the location being watched.
    """


# - DIR AT LOCATION


@dataclasses.dataclass
class DirCreatedWithinWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A directory has been created on the system within a dir being monitored.
    """


@dataclasses.dataclass
class DirUpdatedWithinWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A dir has been updated at the location being watched.
    """


@dataclasses.dataclass
class DirMovedWithinWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A dir has been moved to the location being watched.
    """

    dir_src_path: Union[str, Path]
    dir_dst_path: Union[str, Path]


@dataclasses.dataclass
class DirMovedOutOfWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A dir has been moved to the location being watched.
    """

    dir_src_path: Union[str, Path]
    dir_dst_path: Union[str, Path]


@dataclasses.dataclass
class DirDeletedFromWatchedDirFSInputEvent(FileFSInputEvent):
    """
    A dir has been deleted from the location being watched.
    """
