kind: IOConfig
implementation: mewbot.io.discord.DiscordIO
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa00
properties:
  token: "[token goes here]"

---

kind: Behaviour
implementation: mewbot.api.v1.Behaviour
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa01
properties:
  name: 'Mewbot based DiceMaiden clone'
triggers:
  - kind: Trigger
    implementation: examples.discord_bots.dice_maiden_clone.DiscordDiceMaidenCommandTrigger
    uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa02
    properties:
      command_prefix: "!r"
conditions: []
actions:
  - kind: Action
    implementation: examples.discord_bots.dice_maiden_clone.DiscordDiceMaidenResponseAction
    uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa03
    properties:
      message: "world"