# SPDX-FileCopyrightText: 2021 - 2023 Mewbot Developers <mewbot@quicksilver.london>
#
# SPDX-License-Identifier: CC-BY-4.0
# An _absolutely_ awful example of using DataSources in mewbot actions.

kind: DataSource
name: vals_for_d6
implementation: mewbot.data.json_data.JsonStringDataSourceListValues
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa00
datatype: int
properties:
  json_string: '[1, 2, 3, 4, 5, 6]'

---

kind: IOConfig
implementation: examples.stdio.StandardConsoleInputOutput
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa00
properties: {}

---

kind: Behaviour
implementation: mewbot.api.v1.Behaviour
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa01
properties:
  name: 'Echo Inputs'
triggers:
  - kind: Trigger
    implementation: mewbot.io.common.AllEventsTrigger
    uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa02
    properties: {}
actions:
  - kind: Action
    implementation: examples.data_sources.RollDiceAction
    uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa04
    properties:
      die: { datasource: vals_for_d6 }
