apiVersion: v1
kind: IOConfig
module: mewbot.io.discord
name: DiscordIO
uuid: 1
properties:
  token: "[token goes here]"

---

apiVersion: v1
kind: Behaviour
module: mewbot.api.v1
name: Behaviour
uuid: 1
properties:
  name: 'Echo Inputs'
triggers:
  - apiVersion: v1
    kind: Trigger
    module: examples.trivial_discord_bot
    name: DiscordTextCommandTrigger
    uuid: 1
    properties:
      command: "!hello"
conditions: []
actions:
  - apiVersion: v1
    kind: Action
    module: examples.trivial_discord_bot
    name: DiscordCommandTextResponse
    uuid: 1
    properties:
      message: "world"
