kind: IOConfig
implementation: mewbot.io.file_system.FileSystemIO
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa00
properties:
  input_path: None
---

kind: Behaviour
implementation: mewbot.api.v1.Behaviour
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa01
properties:
  name: 'Target File Change Alerts - but with None path - so it just sits here - hopefully not eating all resources'
triggers:
  - kind: Trigger
    implementation: examples.file_system_bots.file_input_monitor_bot.FileSystemAllCommandTrigger
    uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa02
    properties: {}
conditions: []
actions:
  - kind: Action
    implementation: examples.file_system_bots.file_input_monitor_bot.FileSystemInputPrintResponse
    uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa03
    properties: {}
