#!/bin/sh

# SPDX-FileCopyrightText: 2021 - 2023 Mewbot Developers <mewbot@quicksilver.london>
#
# SPDX-License-Identifier: BSD-2-Clause

COPYRIGHT="Mewbot Developers <mewbot@quicksilver.london>"

LICENSE="BSD-2-Clause"

find . \
	-path './.git' -prune -o \
	-path './.reuse' -prune -o \
	-path './LICENSES' -prune -o \
	-path './venv' -prune -o \
	-type f \
	-exec \
reuse addheader --merge-copyrights --copyright "$COPYRIGHT" --license "$LICENSE" --skip-unrecognised '{}' +
