# SPDX-FileCopyrightText: 2021 Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
#
# SPDX-License-Identifier: BSD-2-Clause

name: Linting

on:
  push:
    branches:
      - mainline
  pull_request_target:

jobs:
  py-lint:
    name: Lint Python code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Load Depedency Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      run:  pip install -r requirements-dev.txt

    - name: Run PyLint
      run: pylint src | python .github/workflows/pylint_to_gh_action.py || true

  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Load Depedency Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      run:  pip install -r requirements-dev.txt

    - name: Run Linters (src)
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}

        black:      true
        black_dir:  src

        flake8:     true
        flake8_dir: src

        mypy:       true
        mypy_dir:   src
        mypy_args:  --strict
        
    - name: Run Linters (examples)
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}

        black:      true
        black_dir:  examples

        flake8:     true
        flake8_dir: examples

        mypy:       true
        mypy_dir:   examples
        mypy_args:  --strict

